blank_issues_enabled: false
contact_links:
  - name: "\U0001F4DA PowerToys user documentation"
    url: https://aka.ms/powertoys-docs
    about: Documentation for users of PowerToys utilities
  - name: "\U0001F4DA PowerToys dev documentation"
    url: https://github.com/microsoft/PowerToys/tree/main/doc/devdocs
    about: Documentation for people interested in developing and contributing for PowerToys
 
